language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pypy3.3-5.5-alpha
env:
- DJANGO=1.4.15
- DJANGO=1.6.7
- DJANGO=1.7
- DJANGO=1.8
- DJANGO=1.9
- DJANGO=1.10
install:
- pip install -q gitversion
- pip install -q Django==$DJANGO
- pip install -q .
- pip install -q coveralls
script:
- python setup.py test
after_success:
- coveralls
matrix:
  exclude:
  - python: 2.6
    env: DJANGO=1.7
  - python: 2.6
    env: DJANGO=1.8
  - python: 2.6
    env: DJANGO=1.9
  - python: 2.6
    env: DJANGO=1.10
  - python: 3.3
    env: DJANGO=1.4.15
  - python: 3.3
    env: DJANGO=1.9
  - python: 3.3
    env: DJANGO=1.10
  - python: 3.4
    env: DJANGO=1.4.15
  - python: 3.5
    env: DJANGO=1.4.15
  - python: 3.5
    env: DJANGO=1.6.7
  - python: 3.5
    env: DJANGO=1.7
  - python: pypy3.3-5.5-alpha
    env: DJANGO=1.4.15
  - python: pypy3.3-5.5-alpha
    env: DJANGO=1.9
  - python: pypy3.3-5.5-alpha
    env: DJANGO=1.10
deploy:
  provider: pypi
  user: LeaChim
  password:
    secure: IuIoDvmYRKjnQQ9wYSPSfKDgG/+8/nDqTj3KUacHt8XCKbjVcbKxsPKz76Zr214iVTqDQUt35w7wIENJSYP0LaHQ42TekwF+TtDcifSzgvQpxyJ0sP9IjqNHaJ6oHa/XXJJWWQjypFLOOUDSMW8t6+dKcrQp/vHctHvVbP1gECA=
  distributions: "bdist_wheel sdist"
  on:
    all_branches: true
    repo: mikebryant/django-autoconfig
    tags: true
    condition: "$DJANGO = 1.9"
